[package]
name = "live-data-view"
version = "0.1.0"
edition = "2024"

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "simple_global"
path = "examples/simple_global.rs"

[dependencies]
thiserror = "2.0.17"

#
flume = "0.11.1"

#
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "*", features = ["full"] }

#
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
